#!/bin/bash

filelist=`ls | grep .c`

for file in $filelist; do
    if [ "$file" == "run_tests" ] 
    then
        continue
    fi 
    current=${file:0:${#file}-2}
    if [ -e $current ]
    then
        rm $current
    fi

    echo "Building $file"
    `gcc $file ../src/*.c -o ${file:0:${#file}-2} -pthread`
    echo "Running $current"
    ./$current
    out=$?
    if [ ! $out -eq 0 ]; then
        echo "Test failed"
        rm $current
        exit 1

    else
        echo "Test passed"
        rm $current
    fi
done;

exit 0
