#!/bin/bash
function echo_red()
{
  tput setaf 1
  echo $1
  tput sgr0
}

function echo_green()
{
  tput setaf 2
  echo $1
  tput sgr0
}

function run_full_suite()
{
  echo "Running unit tests..."
  pushd test/unit
  ./run_tests
  if [ $? != 0 ]; then
    exit 1
  fi
  popd 
}

function run_single_test()
{
  echo "WIP: Run single test"
}

if [ -z "$1" ]; then 
  run_full_suite
else
  run_single_test
fi

exit 0
