.TH "bug Directory Reference" 3 "Sat Jun 7 2014" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBjnxcheck\&.h\fP"
.br
.ti -1c
.RI "file \fBjnxlog\&.h\fP"
.br
.RI "\fISimple logger that allows program output to be captured to file\&. It allows one log file per process only\&. \fP"
.in -1c
