.TH "mem Directory Reference" 3 "Tue Apr 8 2014" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mem Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBjnxmem\&.h\fP"
.br
.RI "\fIThe API for jnxlibc's implementation of simple memory management for DEBUG mode\&. \fP"
.in -1c
