.TH "src Directory Reference" 3 "Fri Sep 20 2013" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBjnxbase64\&.h\fP"
.br
.RI "\fIThe API for jnxlibc's implementation of Base-64 encoder and decoder\&. \fP"
.ti -1c
.RI "file \fBjnxbtree\&.h\fP"
.br
.RI "\fIThe API for jnxlibc's implementation of B-trees\&. \fP"
.ti -1c
.RI "file \fBjnxfile\&.h\fP"
.br
.RI "\fIFile manipulation, read/write, kvp plucking and recursive deletion\&. \fP"
.ti -1c
.RI "file \fBjnxhash\&.h\fP"
.br
.RI "\fIAPI for jnxlibc's implementation of hashmap\&. \fP"
.ti -1c
.RI "file \fBjnxlist\&.h\fP"
.br
.RI "\fIAPI for jnxlibc implementation of list\&. \fP"
.ti -1c
.RI "file \fBjnxlog\&.h\fP"
.br
.RI "\fISimple logger that allows program output to be captured to file\&. It allows one log file per process only\&. \fP"
.ti -1c
.RI "file \fBjnxnetwork\&.h\fP"
.br
.RI "\fIThe API for jnxlibc networking (includes TCP, UDP ) \fP"
.ti -1c
.RI "file \fBjnxstack\&.h\fP"
.br
.RI "\fIAPI for jnxlibc implementation of stack data structure\&. \fP"
.ti -1c
.RI "file \fBjnxstring\&.h\fP"
.br
.RI "\fImanipulate char* by joining \fP"
.ti -1c
.RI "file \fBjnxterm\&.h\fP"
.br
.RI "\fIterminal manipulation of colours, stdout and loading spinnders \fP"
.ti -1c
.RI "file \fBjnxvector\&.h\fP"
.br
.RI "\fIThe API for jnxlibc's implementation of vector\&. \fP"
.in -1c
