.TH "sys Directory Reference" 3 "Fri Feb 21 2014" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sys Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBjnxlog\&.h\fP"
.br
.RI "\fISimple logger that allows program output to be captured to file\&. It allows one log file per process only\&. \fP"
.ti -1c
.RI "file \fBjnxstring\&.h\fP"
.br
.RI "\fImanipulate char* by joining \fP"
.ti -1c
.RI "file \fBjnxterm\&.h\fP"
.br
.RI "\fIterminal manipulation of colours, stdout and loading spinnders \fP"
.in -1c
