.TH "src Directory Reference" 3 "Fri Feb 21 2014" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBalg\fP"
.br
.ti -1c
.RI "directory \fBbug\fP"
.br
.ti -1c
.RI "directory \fBdat\fP"
.br
.ti -1c
.RI "directory \fBio\fP"
.br
.ti -1c
.RI "directory \fBmem\fP"
.br
.ti -1c
.RI "directory \fBnet\fP"
.br
.ti -1c
.RI "directory \fBsys\fP"
.br
.ti -1c
.RI "directory \fBthr\fP"
.br
.in -1c
