.TH "sys Directory Reference" 3 "Sun Feb 1 2015" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sys Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBjnxstring\&.h\fP"
.br
.RI "\fImanipulate jnx_char* by joining \fP"
.ti -1c
.RI "file \fBjnxterm\&.h\fP"
.br
.RI "\fIterminal manipulation of colours, stdout and loading spinnders \fP"
.ti -1c
.RI "file \fBjnxtypes\&.h\fP"
.br
.in -1c
