.TH "alg Directory Reference" 3 "Sun Feb 1 2015" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
alg Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBjnxencoder\&.h\fP"
.br
.ti -1c
.RI "file \fBjnxguid\&.h\fP"
.br
.ti -1c
.RI "file \fBjnxquicksort\&.h\fP"
.br
.RI "\fIThe API for sorting arrays of void* data items that can be ordered, via Quicksort algorithm with median-of-three pivot choice strategy\&. \fP"
.in -1c
