.TH "alg Directory Reference" 3 "Mon Apr 7 2014" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
alg Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBjnxbase64\&.h\fP"
.br
.RI "\fIThe API for jnxlibc's implementation of Base-64 encoder and decoder\&. \fP"
.in -1c
