.TH "B_tree_record" 3 "Fri Sep 20 2013" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
B_tree_record \- 
.PP
Internal representation of a (key, value) pair\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxbtree\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBkey\fP"
.br
.ti -1c
.RI "void * \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Internal representation of a (key, value) pair\&. 
.SH "Member Data Documentation"
.PP 
.SS "void* B_tree_record::key"
The key for the record\&. 
.SS "void* B_tree_record::value"
The value for the record\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
