.TH "bucketel" 3 "Fri Sep 20 2013" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bucketel \- 
.PP
Internal container for a key value pair\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxhash\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBorigin_key\fP"
.br
.ti -1c
.RI "const char * \fBorigin_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Internal container for a key value pair\&. 
.SH "Member Data Documentation"
.PP 
.SS "char* bucketel::origin_key"

.SS "const char* bucketel::origin_value"


.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
