.TH "hashel" 3 "Tue Oct 1 2013" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hashel \- 
.PP
Internal container for key value pair lists\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxhash\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBjnx_list\fP * \fBbucket\fP"
.br
.ti -1c
.RI "int \fBbucket_len\fP"
.br
.ti -1c
.RI "int \fBused\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Internal container for key value pair lists\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBjnx_list\fP* hashel::bucket"

.SS "int hashel::bucket_len"

.SS "int hashel::used"


.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
