.TH "hashmap" 3 "Tue Oct 1 2013" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hashmap \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxhash\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBjnx_hash_element\fP * \fBdata\fP"
.br
.ti -1c
.RI "unsigned int \fBsize\fP"
.br
.ti -1c
.RI "unsigned int \fBused_up\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBjnx_hash_element\fP* hashmap::data"

.SS "unsigned int hashmap::size"

.SS "unsigned int hashmap::used_up"


.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
