.TH "jnx_thread_attributes" 3 "Wed Apr 16 2014" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jnx_thread_attributes \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxthread\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBhas_custom_attr\fP"
.br
.ti -1c
.RI "pthread_attr_t * \fBsystem_attributes\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int jnx_thread_attributes::has_custom_attr"

.SS "pthread_attr_t* jnx_thread_attributes::system_attributes"


.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
