.TH "jnx_socket" 3 "Wed Apr 16 2014" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jnx_socket \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxsocket\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBisclosed\fP"
.br
.ti -1c
.RI "int \fBsocket\fP"
.br
.ti -1c
.RI "unsigned int \fBaddrfamily\fP"
.br
.ti -1c
.RI "ssize_t \fBstype\fP"
.br
.ti -1c
.RI "char * \fBipaddress\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned int jnx_socket::addrfamily"

.SS "char* jnx_socket::ipaddress"

.SS "int jnx_socket::isclosed"

.SS "int jnx_socket::socket"

.SS "ssize_t jnx_socket::stype"


.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
