.TH "jnx_queue" 3 "Mon Apr 7 2014" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jnx_queue \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxqueue\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBjnx_list\fP * \fBlist\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBjnx_list\fP* jnx_queue::list"


.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
