.TH "jnx_encoder" 3 "Sun Feb 1 2015" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jnx_encoder \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxencoder\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBjnx_char\fP * \fBb64_encoding_table\fP"
.br
.ti -1c
.RI "\fBjnx_char\fP * \fBb64_decoding_table\fP"
.br
.ti -1c
.RI "\fBjnx_uint32\fP * \fBb64_mod_table\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBjnx_char\fP* jnx_encoder::b64_decoding_table"

.SS "\fBjnx_char\fP* jnx_encoder::b64_encoding_table"

.SS "\fBjnx_uint32\fP* jnx_encoder::b64_mod_table"


.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
