.TH "jnx_snode" 3 "Sun Apr 27 2014" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jnx_snode \- 
.PP
Node represents an element of the stack\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxstack\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fB_data\fP"
.br
.ti -1c
.RI "struct \fBjnx_snode\fP * \fBnext_node\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Node represents an element of the stack\&. 
.SH "Member Data Documentation"
.PP 
.SS "void* jnx_snode::_data"

.SS "struct \fBjnx_snode\fP* jnx_snode::next_node"


.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
