.TH "jnx_vector_record" 3 "Fri Sep 20 2013" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jnx_vector_record \- 
.PP
An internal implementation of record data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxvector\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBused\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An internal implementation of record data\&. 
.SH "Member Data Documentation"
.PP 
.SS "void* jnx_vector_record::data"

.SS "int jnx_vector_record::used"


.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
