.TH "jnx_guid" 3 "Sun Feb 1 2015" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jnx_guid \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxguid\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBjnx_uint8\fP \fBguid\fP [16]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBjnx_uint8\fP jnx_guid::guid[16]"


.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
