.TH "jnx_vector_record" 3 "Sun Feb 1 2015" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jnx_vector_record \- An internal implementation of record data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxvector\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBjnx_int32\fP \fBused\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An internal implementation of record data\&. 
.SH "Member Data Documentation"
.PP 
.SS "void* jnx_vector_record::data"

.SS "\fBjnx_int32\fP jnx_vector_record::used"


.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
