.TH "jnx_mem_item" 3 "Sat Jan 25 2014" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jnx_mem_item \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxmem\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBptr\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "char * \fBfile\fP"
.br
.ti -1c
.RI "char * \fBfunction\fP"
.br
.ti -1c
.RI "int \fBline\fP"
.br
.ti -1c
.RI "\fBjnx_mem_memtrace_state\fP \fBstate\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char* jnx_mem_item::file"

.SS "char* jnx_mem_item::function"

.SS "int jnx_mem_item::line"

.SS "void* jnx_mem_item::ptr"

.SS "size_t jnx_mem_item::size"

.SS "\fBjnx_mem_memtrace_state\fP jnx_mem_item::state"


.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
