.TH "jnx_vector" 3 "Fri Sep 20 2013" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jnx_vector \- 
.PP
The external structure and interface for jnx vector\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxvector\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "\fBjnx_vector_record\fP ** \fBvector\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The external structure and interface for jnx vector\&. 
.SH "Member Data Documentation"
.PP 
.SS "int jnx_vector::count"

.SS "\fBjnx_vector_record\fP** jnx_vector::vector"


.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
