.TH "jnx_thread_mutex" 3 "Sat Jun 7 2014" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jnx_thread_mutex \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxthread\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "pthread_mutex_t \fBsystem_mutex\fP"
.br
.ti -1c
.RI "int \fBis_initialized\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int jnx_thread_mutex::is_initialized"

.SS "pthread_mutex_t jnx_thread_mutex::system_mutex"


.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
