.TH "jnx_vector2D" 3 "Sun Feb 1 2015" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jnx_vector2D \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxtypes\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBjnx_float\fP \fBx\fP"
.br
.ti -1c
.RI "\fBjnx_float\fP \fBy\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBjnx_float\fP jnx_vector2D::x"

.SS "\fBjnx_float\fP jnx_vector2D::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
