.TH "jnx_file_kvp_node" 3 "Fri Sep 20 2013" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jnx_file_kvp_node \- 
.PP
An internal representation of the kvp node populated when used in key value pair retrieval from a file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxfile\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBkey\fP"
.br
.ti -1c
.RI "char * \fBvalue\fP"
.br
.ti -1c
.RI "struct \fBjnx_file_kvp_node\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An internal representation of the kvp node populated when used in key value pair retrieval from a file\&. 
.SH "Member Data Documentation"
.PP 
.SS "char* jnx_file_kvp_node::key"

.SS "struct \fBjnx_file_kvp_node\fP* jnx_file_kvp_node::next"

.SS "char* jnx_file_kvp_node::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
