.TH "jnx_vector" 3 "Sun Feb 1 2015" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jnx_vector \- The external structure and jnx_int32erface for jnx vector\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxvector\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBjnx_int32\fP \fBcount\fP"
.br
.ti -1c
.RI "\fBjnx_vector_record\fP ** \fBvector\fP"
.br
.ti -1c
.RI "\fBjnx_thread_mutex\fP * \fBinternal_lock\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The external structure and jnx_int32erface for jnx vector\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBjnx_int32\fP jnx_vector::count"

.SS "\fBjnx_thread_mutex\fP* jnx_vector::internal_lock"

.SS "\fBjnx_vector_record\fP** jnx_vector::vector"


.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
