.TH "jnx_stack" 3 "Sat Jun 7 2014" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jnx_stack \- 
.PP
Represents the stack data structure as seen by the user\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxstack\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBjnx_snode\fP * \fBtop\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "\fBjnx_thread_mutex\fP * \fBinternal_lock\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents the stack data structure as seen by the user\&. 
.SH "Member Data Documentation"
.PP 
.SS "int jnx_stack::count"

.SS "\fBjnx_thread_mutex\fP* jnx_stack::internal_lock"

.SS "struct \fBjnx_snode\fP* jnx_stack::top"


.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
