.TH "jnx_thread" 3 "Sun Mar 2 2014" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jnx_thread \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxthread\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "void * \fBargs\fP"
.br
.ti -1c
.RI "\fBjnx_thread_attributes\fP * \fBattributes\fP"
.br
.ti -1c
.RI "pthread_t \fBsystem_thread\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "void* jnx_thread::args"

.SS "\fBjnx_thread_attributes\fP* jnx_thread::attributes"

.SS "int jnx_thread::id"

.SS "pthread_t jnx_thread::system_thread"


.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
