.TH "jnxdebug.h" 3 "Sun Mar 2 2014" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jnxdebug.h \- 
.PP
The API for jnxlibc's debugging tools\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <signal\&.h>\fP
.br
\fC#include 'jnxlist\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_TRACE\fP   40"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBjnx_debug_stacktrace\fP (char *path, int counter, int signals[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
The API for jnxlibc's debugging tools\&. 

#include <jnxc_headers/jnxdebug\&.h> 
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX_TRACE   40"

.SH "Function Documentation"
.PP 
.SS "void jnx_debug_stacktrace (char *path, intcounter, intsignals[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
