.TH "jnxlog.h" 3 "Sat Jun 7 2014" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jnxlog.h \- 
.PP
Simple logger that allows program output to be captured to file\&. It allows one log file per process only\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdarg\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_LOG_SIZE\fP   2048"
.br
.ti -1c
.RI "#define \fBMAX_ARG_SIZE\fP   1024"
.br
.ti -1c
.RI "#define \fBLOGTEMPLATE\fP   '[%s][%s][%s:%s:%d]'"
.br
.ti -1c
.RI "#define \fBJCRITICAL\fP   'CRITICAL'"
.br
.ti -1c
.RI "#define \fBJALERT\fP   'ALERT'"
.br
.ti -1c
.RI "#define \fBJCAUTION\fP   'CAUTION'"
.br
.ti -1c
.RI "#define \fBJNOTICE\fP   'NOTICE'"
.br
.ti -1c
.RI "#define \fBJDEBUG\fP   'DEBUG'"
.br
.ti -1c
.RI "#define \fBJNORMAL\fP   'NORMAL'"
.br
.ti -1c
.RI "#define \fBJNX_LOGC\fP(LEVEL, X,\&.\&.\&.)   \fBjnx_log\fP(LEVEL,__FILE__,__FUNCTION__,__LINE__,X, ## __VA_ARGS__)"
.br
.RI "\fIlog to console \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBJNX_LOG_LEVEL\fP \fBJNX_LOG_LEVEL\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBJNX_LOG_LEVEL\fP { \fBJLOG_CRITICAL\fP, \fBJLOG_ALERT\fP, \fBJLOG_CAUTION\fP, \fBJLOG_NOTICE\fP, \fBJLOG_DEBUG\fP, \fBJLOG_NORMAL\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBjnx_log\fP (\fBJNX_LOG_LEVEL\fP level, const char *file, const char *function, const int line, const char *format,\&.\&.\&.)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Simple logger that allows program output to be captured to file\&. It allows one log file per process only\&. 

#include <jnxc_headers/jnxlog\&.h> 
.SH "Macro Definition Documentation"
.PP 
.SS "#define JALERT   'ALERT'"

.SS "#define JCAUTION   'CAUTION'"

.SS "#define JCRITICAL   'CRITICAL'"

.SS "#define JDEBUG   'DEBUG'"

.SS "#define JNORMAL   'NORMAL'"

.SS "#define JNOTICE   'NOTICE'"

.SS "#define JNX_LOGC(LEVEL, X, \&.\&.\&.)   \fBjnx_log\fP(LEVEL,__FILE__,__FUNCTION__,__LINE__,X, ## __VA_ARGS__)"

.PP
log to console JNX_LOGC 
.SS "#define LOGTEMPLATE   '[%s][%s][%s:%s:%d]'"

.SS "#define MAX_ARG_SIZE   1024"

.SS "#define MAX_LOG_SIZE   2048"

.SH "Typedef Documentation"
.PP 
.SS "typedef enum \fBJNX_LOG_LEVEL\fP  \fBJNX_LOG_LEVEL\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBJNX_LOG_LEVEL\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIJLOG_CRITICAL \fP\fP
.TP
\fB\fIJLOG_ALERT \fP\fP
.TP
\fB\fIJLOG_CAUTION \fP\fP
.TP
\fB\fIJLOG_NOTICE \fP\fP
.TP
\fB\fIJLOG_DEBUG \fP\fP
.TP
\fB\fIJLOG_NORMAL \fP\fP
.SH "Function Documentation"
.PP 
.SS "size_t jnx_log (\fBJNX_LOG_LEVEL\fPlevel, const char *file, const char *function, const intline, const char *format, \&.\&.\&.)"

.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
