.TH "jnxlist.h" 3 "Fri Feb 21 2014" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jnxlist.h \- 
.PP
API for jnxlibc implementation of list\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBnode\fP"
.br
.RI "\fINode represents a link in the list\&. \fP"
.ti -1c
.RI "struct \fBlist\fP"
.br
.RI "\fIRepresents the list data structure as seen by the user\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBnode\fP \fBjnx_node\fP"
.br
.RI "\fINode represents a link in the list\&. \fP"
.ti -1c
.RI "typedef struct \fBlist\fP \fBjnx_list\fP"
.br
.RI "\fIRepresents the list data structure as seen by the user\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBjnx_list\fP * \fBjnx_list_create\fP (void)"
.br
.RI "\fIReturns newly created list\&. \fP"
.ti -1c
.RI "void \fBjnx_list_add\fP (\fBjnx_list\fP *A, void *_datain)"
.br
.RI "\fIAccepts a void pointer for input with list\&. \fP"
.ti -1c
.RI "void * \fBjnx_list_remove\fP (\fBjnx_list\fP **A)"
.br
.ti -1c
.RI "void \fBjnx_list_destroy\fP (\fBjnx_list\fP **A)"
.br
.in -1c
.SH "Detailed Description"
.PP 
API for jnxlibc implementation of list\&. 

#include <jnxc_headers/jnxlist\&.h> 
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBlist\fP  \fBjnx_list\fP"

.PP
Represents the list data structure as seen by the user\&. 
.SS "typedef struct \fBnode\fP  \fBjnx_node\fP"

.PP
Node represents a link in the list\&. 
.SH "Function Documentation"
.PP 
.SS "jnx_list_add (\fBjnx_list\fP *A, void *_datain)"

.PP
Accepts a void pointer for input with list\&. 
.PP
\fBParameters:\fP
.RS 4
\fIA\fP is the target list 
.br
\fI_datain\fP is the data to insert 
.RE
.PP

.SS "jnx_list_create (void)"

.PP
Returns newly created list\&. 
.PP
\fBReturns:\fP
.RS 4
jnx_list* to a newly created list of 0 length 
.RE
.PP

.SS "void jnx_list_destroy (\fBjnx_list\fP **A)"

.SS "void* jnx_list_remove (\fBjnx_list\fP **A)"

.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
