.TH "jnxlog.h" 3 "Fri Feb 21 2014" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jnxlog.h \- 
.PP
Simple logger that allows program output to be captured to file\&. It allows one log file per process only\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdarg\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_LOG_SIZE\fP   2048"
.br
.ti -1c
.RI "#define \fBMAX_ARG_SIZE\fP   1024"
.br
.ti -1c
.RI "#define \fBJNX_LOG_PATH\fP(X)   \fBjnx_log_file_setup\fP(X);"
.br
.RI "\fIset the log path \fP"
.ti -1c
.RI "#define \fBJNX_LOGC\fP(X,\&.\&.\&.)   \fBjnx_log\fP(\fBLOG_CONSOLE\fP,__FILE__,__FUNCTION__,__LINE__,X, ## __VA_ARGS__)"
.br
.RI "\fIlog to console \fP"
.ti -1c
.RI "#define \fBJNX_LOGF\fP(X,\&.\&.\&.)   \fBjnx_log\fP(\fBLOG_FILE\fP,__FILE__,__FUNCTION__,__LINE__,X,  ## __VA_ARGS__)"
.br
.RI "\fIlog to file \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBlogtype\fP \fBlogtype\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBlogtype\fP { \fBLOG_FILE\fP, \fBLOG_CONSOLE\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBjnx_log_file_setup\fP (char *path)"
.br
.ti -1c
.RI "size_t \fBjnx_log\fP (const \fBlogtype\fP l, const char *file, const char *function, const int line, const char *format,\&.\&.\&.)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Simple logger that allows program output to be captured to file\&. It allows one log file per process only\&. 

#include <jnxc_headers/jnxlog\&.h> 
.SH "Macro Definition Documentation"
.PP 
.SS "#define JNX_LOG_PATH(X)   \fBjnx_log_file_setup\fP(X);"

.PP
set the log path JNX_LOG_PATH 
.SS "#define JNX_LOGC(X, \&.\&.\&.)   \fBjnx_log\fP(\fBLOG_CONSOLE\fP,__FILE__,__FUNCTION__,__LINE__,X, ## __VA_ARGS__)"

.PP
log to console JNX_LOGC 
.SS "#define JNX_LOGF(X, \&.\&.\&.)   \fBjnx_log\fP(\fBLOG_FILE\fP,__FILE__,__FUNCTION__,__LINE__,X,  ## __VA_ARGS__)"

.PP
log to file JNX_LOGF 
.SS "#define MAX_ARG_SIZE   1024"

.SS "#define MAX_LOG_SIZE   2048"

.SH "Typedef Documentation"
.PP 
.SS "typedef enum \fBlogtype\fP \fBlogtype\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBlogtype\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILOG_FILE \fP\fP
.TP
\fB\fILOG_CONSOLE \fP\fP
.SH "Function Documentation"
.PP 
.SS "size_t jnx_log (const \fBlogtype\fPl, const char *file, const char *function, const intline, const char *format, \&.\&.\&.)"

.SS "int jnx_log_file_setup (char *path)"

.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
