.TH "jnxstring.h" 3 "Sun Feb 1 2015" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jnxstring.h \- manipulate jnx_char* by joining  

.SH SYNOPSIS
.br
.PP
\fC#include 'jnxtypes\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBjnx_char\fP * \fBjnx_string_joincreate\fP (\fBjnx_char\fP *destination, \fBjnx_char\fP *buf)"
.br
.RI "\fIFunction that joins destination and buf and returns the new string\&. \fP"
.ti -1c
.RI "void \fBjnx_string_join\fP (\fBjnx_char\fP **destination, \fBjnx_char\fP *buf)"
.br
.RI "\fIFunction that appends buf to destination without recreating any strings\&. \fP"
.ti -1c
.RI "\fBjnx_char\fP * \fBjnx_string_itos\fP (\fBjnx_int32\fP input)"
.br
.in -1c
.SH "Detailed Description"
.PP 
manipulate jnx_char* by joining 

#include <jnxc_headers/jnxstring\&.h> 
.SH "Function Documentation"
.PP 
.SS "\fBjnx_char\fP* jnx_string_itos (\fBjnx_int32\fP input)"

.SS "jnx_string_join (\fBjnx_char\fP ** destination, \fBjnx_char\fP * buf)"

.PP
Function that appends buf to destination without recreating any strings\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdestination\fP this requires a pointer to the memory for the destination string 
.br
\fIbuf\fP takes a buffer and appends it to the destination string 
.RE
.PP

.SS "jnx_string_joincreate (\fBjnx_char\fP * destination, \fBjnx_char\fP * buf)"

.PP
Function that joins destination and buf and returns the new string\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdestination\fP the destination string for joining, must be malloced 
.br
\fIbuf\fP the input buffer to be joined to destination
.RE
.PP
\fBReturns:\fP
.RS 4
returns a new jnx_char* string
.RE
.PP
\fBWarning:\fP
.RS 4
user is responsible for memory management of new returned string and originals 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
