.TH "jnxstring.h" 3 "Fri Feb 21 2014" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jnxstring.h \- 
.PP
manipulate char* by joining  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBjnx_string_joincreate\fP (char *destination, char *buf)"
.br
.RI "\fIFunction that joins destination and buf and returns the new string\&. \fP"
.ti -1c
.RI "void \fBjnx_string_join\fP (char **destination, char *buf)"
.br
.RI "\fIFunction that appends buf to destination without recreating any strings\&. \fP"
.ti -1c
.RI "char * \fBjnx_string_itos\fP (int input)"
.br
.RI "\fIFunction that convets passed in integer to its string representation\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
manipulate char* by joining 

#include <jnxc_headers/jnxstring\&.h> 
.SH "Function Documentation"
.PP 
.SS "jnx_string_itos (intinput)"

.PP
Function that convets passed in integer to its string representation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinput\fP requires an int input for conversion
.RE
.PP
\fBReturns:\fP
.RS 4
returns a string on the stack which is the converted input\&. NULL is returned on failure 
.RE
.PP

.SS "jnx_string_join (char **destination, char *buf)"

.PP
Function that appends buf to destination without recreating any strings\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdestination\fP this requires a pointer to the memory for the destination string 
.br
\fIbuf\fP takes a buffer and appends it to the destination string 
.RE
.PP

.SS "jnx_string_joincreate (char *destination, char *buf)"

.PP
Function that joins destination and buf and returns the new string\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdestination\fP the destination string for joining, must be malloced 
.br
\fIbuf\fP the input buffer to be joined to destination
.RE
.PP
\fBReturns:\fP
.RS 4
returns a new char* string
.RE
.PP
\fBWarning:\fP
.RS 4
user is responsible for memory management of new returned string and originals 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
