.TH "jnxthread" 3 "Fri Feb 21 2014" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jnxthread \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxthread\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "void * \fBargs\fP"
.br
.ti -1c
.RI "\fBjnxthread_attributes\fP * \fBattributes\fP"
.br
.ti -1c
.RI "pthread_t \fBsystem_thread\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "void* jnxthread::args"

.SS "\fBjnxthread_attributes\fP* jnxthread::attributes"

.SS "int jnxthread::id"

.SS "pthread_t jnxthread::system_thread"


.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
