.TH "jnxtypes.h" 3 "Sun Feb 1 2015" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jnxtypes.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBjnx_vector2D\fP"
.br
.ti -1c
.RI "struct \fBjnx_vector3D\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef char \fBjnx_char\fP"
.br
.ti -1c
.RI "typedef signed char \fBjnx_signed_char\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBjnx_unsigned_char\fP"
.br
.ti -1c
.RI "typedef int \fBjnx_int\fP"
.br
.ti -1c
.RI "typedef signed int \fBjnx_signed_int\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBjnx_unsigned_int\fP"
.br
.ti -1c
.RI "typedef long int \fBjnx_long_int\fP"
.br
.ti -1c
.RI "typedef uint8_t \fBjnx_uint8\fP"
.br
.ti -1c
.RI "typedef uint32_t \fBjnx_uint32\fP"
.br
.ti -1c
.RI "typedef uint64_t \fBjnx_uint64\fP"
.br
.ti -1c
.RI "typedef int32_t \fBjnx_int32\fP"
.br
.ti -1c
.RI "typedef float \fBjnx_float\fP"
.br
.ti -1c
.RI "typedef struct \fBjnx_vector2D\fP \fBjnx_vector2D\fP"
.br
.ti -1c
.RI "typedef struct \fBjnx_vector3D\fP \fBjnx_vector3D\fP"
.br
.ti -1c
.RI "typedef size_t \fBjnx_size\fP"
.br
.ti -1c
.RI "typedef ssize_t \fBjnx_ssize\fP"
.br
.ti -1c
.RI "typedef double \fBjnx_double\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef char \fBjnx_char\fP"

.SS "typedef double \fBjnx_double\fP"

.SS "typedef float \fBjnx_float\fP"

.SS "typedef int \fBjnx_int\fP"

.SS "typedef int32_t \fBjnx_int32\fP"

.SS "typedef long int \fBjnx_long_int\fP"

.SS "typedef signed char \fBjnx_signed_char\fP"

.SS "typedef signed int \fBjnx_signed_int\fP"

.SS "typedef size_t \fBjnx_size\fP"

.SS "typedef ssize_t \fBjnx_ssize\fP"

.SS "typedef uint32_t \fBjnx_uint32\fP"

.SS "typedef uint64_t \fBjnx_uint64\fP"

.SS "typedef uint8_t \fBjnx_uint8\fP"

.SS "typedef unsigned char \fBjnx_unsigned_char\fP"

.SS "typedef unsigned int \fBjnx_unsigned_int\fP"

.SS "typedef struct \fBjnx_vector2D\fP \fBjnx_vector2D\fP"

.SS "typedef struct \fBjnx_vector3D\fP \fBjnx_vector3D\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
