.TH "jnxthread_mutex" 3 "Mon Feb 17 2014" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jnxthread_mutex \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxthread\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "pthread_mutex_t \fBsystem_mutex\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "pthread_mutex_t jnxthread_mutex::system_mutex"


.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
