.TH "list" 3 "Fri Sep 20 2013" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
list \- 
.PP
Represents the list data structure as seen by the user\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxlist\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnode\fP * \fBhead\fP"
.br
.ti -1c
.RI "int \fBcounter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents the list data structure as seen by the user\&. 
.SH "Member Data Documentation"
.PP 
.SS "int list::counter"

.SS "struct \fBnode\fP* list::head"


.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
