.TH "list" 3 "Sun Feb 1 2015" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
list \- Represents the list data structure as seen by the user\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxlist\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnode\fP * \fBhead\fP"
.br
.ti -1c
.RI "struct \fBnode\fP * \fBtail\fP"
.br
.ti -1c
.RI "\fBjnx_int32\fP \fBcounter\fP"
.br
.ti -1c
.RI "\fBjnx_thread_mutex\fP * \fBinternal_lock\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents the list data structure as seen by the user\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBjnx_int32\fP list::counter"

.SS "struct \fBnode\fP* list::head"

.SS "\fBjnx_thread_mutex\fP* list::internal_lock"

.SS "struct \fBnode\fP* list::tail"


.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
