.TH "node" 3 "Fri Sep 20 2013" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node \- 
.PP
Node represents a link in the list\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxlist\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fB_data\fP"
.br
.ti -1c
.RI "struct \fBnode\fP * \fBnext_node\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Node represents a link in the list\&. 

Node represents an element of the stack\&. 
.SH "Member Data Documentation"
.PP 
.SS "void * node::_data"

.SS "struct \fBnode\fP * node::next_node"


.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
