.TH "stack" 3 "Tue Oct 1 2013" "jnxlibc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stack \- 
.PP
Represents the stack data structure as seen by the user\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'jnxstack\&.h'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnode\fP * \fBtop\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents the stack data structure as seen by the user\&. 
.SH "Member Data Documentation"
.PP 
.SS "int stack::count"

.SS "struct \fBnode\fP* stack::top"


.SH "Author"
.PP 
Generated automatically by Doxygen for jnxlibc from the source code\&.
