#!/bin/bash
function echo_red()
{
    tput setaf 1
    echo $1
    tput sgr0
}

function echo_green()
{
    tput setaf 2
    echo $1
    tput sgr0
}

echo "Running unit tests..."
pushd unit
./run_tests
popd 
echo "Running performance tests"
pushd performance
./run_tests
popd
exit 0
