#!/bin/bash
OS=`uname`
if [ "$OS" == "Darwin" ]; then
	echo "Building with Clang"
COMPILER=clang
else
	echo "Building with GCC"
COMPILER=gcc
fi
function echo_red()
{
    tput setaf 1
    echo $1
    tput sgr0
}

function echo_green()
{
    tput setaf 2
    echo $1
    tput sgr0
}

filelist=`ls *.c`
for file in $filelist; do
    if [ "$file" == "run_tests" ] 
    then
        continue
    fi 
    current=${file:0:${#file}-2}
    if [ -e $current ]
    then
        rm $current
    fi

	echo "Running next test for --> ${file}"
	`$COMPILER $file ../../build/*.c -I../../build -o ${file:0:${#file}-2} -pthread -w -rdynamic`
    ./$current
    out=$?
    if [ ! $out -eq 0 ]; then
        echo_red "Test failed"
        rm $current
        exit 1

    else
        echo_green "Test passed"
        rm $current
    fi
done;

exit 0
